name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  delete-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Delete the gh-pages branch
        uses: ad-m/delete-gh-pages@v1
        with:
          token: ${{ secrets.ACTION_TOKEN }}

  build:
    needs: delete-gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies and build
        run: npm i
      - name: Build
        run: npm run build

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTION_TOKEN }}
          external_repository: VCrishna/MyPortfolio
          publish_branch: gh-pages
          publish_dir: build
