name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to the branch where your React app's source code is

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12 # Use the Node.js version required by your React app

      - name: Install dependencies and build
        run: |
          npm ci
          npm i
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTION_TOKEN }}
          external_repository: VCrishna/MyPortfolio
          publish_branch: depploy
          publish_dir: build
